# Check incoming data

In [2]:
import pandas as pd
import geopandas as gpd

data_file = "../data/input_viabel/Machelen_Data_Shapefiles/Wegsectieonderdeel_SPLIT.shp"
df = gpd.read_file(data_file)

In [3]:
print(df.head())
df.columns

  bestemm verhtype wegfunct   bouwdate MTRGLGEM LBLMTRGLGE VERSION InfoScope  \
0      RW       BP      ERF 1950-01-01       GN       None       1      None
1      RW       BP      ERF 1950-01-01       GN       None       1      None
2      RW       BP       VW 1950-01-01       GN       None       1      None
3      RW       BP      ERF 1950-01-01       GN       None       1      None
4      RW       BS      ERF 1950-01-01       GN       None       1      None

   Gemeente Deelgemeen  ...     Edited                 Straat       isN  \
0  Machelen     Diegem  ... 2024-06-10  OUDE HAACHTSESTEENWEG  0.860432
1  Machelen     Diegem  ... 2024-06-10          REGIMENTSBERG  0.872750
2  Machelen   Machelen  ... 2024-06-10      KONING ALBERTLAAN  0.900000
3  Machelen     Diegem  ... 2024-06-10   SINT-KORNELIUSSTRAAT  0.769092
4  Machelen     Diegem  ... 2024-06-10  LEONARDO DA VINCILAAN  0.773281

        igN diff_igc_i  diff_igc_F  diff_igN_F  Shape_STAr  Shape_STLe  \
0  0.808994  -0.065682    0.364534    0.430216  128.195551   64.052691
1  0.871160  -0.004633    0.431742    0.436375  698.000759  245.558450
2  0.900000   0.000000    0.450000    0.450000   91.788270   43.158837
3  0.769092  -0.013091    0.371455    0.384546   74.478979   41.803482
4  0.757765  -0.031292    0.355349    0.386641  250.087422   95.535038

                                            geometry
0  POLYGON ((154638.46 176161.767, 154637.994 176...
1  POLYGON ((154763.474 175757.875, 154764.679 17...
2  POLYGON ((154800.95 177658.331, 154803.628 177...
3  POLYGON ((154563.976 176024.966, 154569.341 17...
4  POLYGON ((156537.507 175820.526, 156544.401 17...

[5 rows x 51 columns]

Index(['bestemm', 'verhtype', 'wegfunct', 'bouwdate', 'MTRGLGEM', 'LBLMTRGLGE',
       'VERSION', 'InfoScope', 'Gemeente', 'Deelgemeen', 'WSO_SPLIT_',
       'WSO_GUID', 'straat_FK', 'gemeent_FK', 'Opmerkinge', 'iv', 'isc', 'igc',
       'F_is', 'F_ig', 'is_mix', 'ig_mix', 'opp', 'wso_id', 'aanvang',
       'eerste_m', 'kwal', 'kwalklas', 'jaar', 'kosten', 'maatreg', 'planjaar',
       'gew_kwal', 'i_rio', 'i_integr', 'mod_date', 'wegsect_FK', 'wijk_FK',
       'Creator', 'Created', 'Editor', 'Edited', 'Straat', 'isN', 'igN',
       'diff_igc_i', 'diff_igc_F', 'diff_igN_F', 'Shape_STAr', 'Shape_STLe',
       'geometry'],
      dtype='object')

In [10]:
x = set(df["wegfunct"].dropna().unique())
x

{'DGW', 'ERF', 'VW'}

In [14]:
# Map road functions (k)
road_function_map = {
    'ERF': 'erf',  # Erffunctie
    'VW': 'verzamel',   # Verzamelweg
    'DGW': 'doorgang'   # Doorgangsweg
}

# Map pavement types (j)
pavement_type_map = {
    'BS': 'asfalt',  # Asfalt (bitumineuze verharding)
    'CS': 'beton',  # Beton
    'BP': 'elementen'   # Elementenverharding
}

y = set(road_function_map.keys())

In [15]:
if set(df["wegfunct"].dropna().unique()).issubset(y):
    print("yes")

yes

In [19]:
col = "wegfunct"
df[f"{col}_original"] = df[col]
mapped = df[col].map(road_function_map)
unmapped = df[col][mapped.isna()].unique()

mapped
unmapped

array([], dtype=object)

In [4]:
df[df["Straat"] == "NOORDSTRAAT"]

,G_staat,G_date,S_index,S_date,WSO_id,V_index,Dofunctie,Verharding,Wegfunctie,Straat,Gemeente,Wegsectie,Guid,Oppervlakt,Prioriteit,DATUM,geometry,functie,verharding
365,0.450000,1950-01-01,0.9,1950-01-01,365,0.000000,RW,BS,VW,NOORDSTRAAT,Machelen,9C828A41-4D7A-4868-812C-FD95402F0F5A,D5784690-7420-431A-A2C1-2F9332954A68,452.070597,1.0,2024-10-06,"POLYGON ((156198.659 179145.718, 156197.557 17...",verzamel,asfalt
366,0.837500,1950-01-01,0.9,1950-01-01,366,0.775000,RW,BS,VW,NOORDSTRAAT,Machelen,9C828A41-4D7A-4868-812C-FD95402F0F5A,D309FA38-60C5-4F85-9A66-A731A7025184,503.296432,1.0,2024-10-06,"POLYGON ((156198.659 179145.718, 156215.104 17...",verzamel,asfalt
906,0.532741,1950-01-01,0.9,1950-01-01,906,0.165482,RW,BS,VW,NOORDSTRAAT,Machelen,F299B090-0A97-4DAD-B3D4-CAE5BF7DD2C4,6568A75F-2E1B-41DB-92FC-22DD97DE138B,1256.212027,1.0,2024-10-06,"POLYGON ((155891.943 179032.286, 155888.192 17...",verzamel,asfalt
907,0.560350,1950-01-01,0.9,1950-01-01,907,0.220699,RW,BS,VW,NOORDSTRAAT,Machelen,F299B090-0A97-4DAD-B3D4-CAE5BF7DD2C4,44E2F64E-373D-4647-9E3F-18DBCEAADDCA,1331.149578,1.0,2024-10-06,"POLYGON ((155891.943 179032.286, 155893.115 17...",verzamel,asfalt
1084,0.450000,1950-01-01,0.9,1950-01-01,1084,0.000000,RW,BS,VW,NOORDSTRAAT,Machelen,079B2E17-B275-48CB-BE91-853FE1CFA5D4,6483B99A-5301-40FA-8715-22E1570CFCAF,785.459803,1.0,2024-10-06,"POLYGON ((156538.75 179285.537, 156530.065 179...",verzamel,asfalt
1085,0.897683,1950-01-01,0.9,1950-01-01,1085,0.895367,RW,BS,VW,NOORDSTRAAT,Machelen,079B2E17-B275-48CB-BE91-853FE1CFA5D4,505A2C45-14BC-4AAA-8D74-F13653270202,819.147236,1.0,2024-10-06,"POLYGON ((156538.75 179285.537, 156540.344 179...",verzamel,asfalt

In [5]:
print(df.shape)
df.columns

(1090, 19)

Index(['G_staat', 'G_date', 'S_index', 'S_date', 'WSO_id', 'V_index',
       'Dofunctie', 'Verharding', 'Wegfunctie', 'Straat', 'Gemeente',
       'Wegsectie', 'Guid', 'Oppervlakt', 'Prioriteit', 'DATUM', 'geometry',
       'functie', 'verharding'],
      dtype='object')

In [6]:
data_file_2 = "../data/output_viabel/Scenario1_Onbeperkt/MaatregelOverzicht.xls"

df_output_org = pd.read_excel(data_file_2)
df_output_org.dropna(axis=0, inplace=True, how='all', subset=['GUID', 'Id'])
df_output_org['Jaar'] = df_output_org.Jaar.astype(int)
df_output_org.drop(columns=['Id', 'GEMEENTE', 'Lengte', 'Planjaar'], inplace=True)
df_output_org['GUID'] = df_output_org.GUID.apply(lambda x: str(x).replace('{', '').replace('}', ''))
print(df_output_org.shape)
df_output_org

(21800, 13)

,GUID,Oppervlakte,type verkeersbelasting,verhardingstype,Visuele index,Aanvangskwaliteit,Jaar eerste maatregel,Kwaliteit,Kwaliteitklasse,Jaar,Kosten,Maatregel,Gewogen kwaliteit
0,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.0,Erftoegangsweg,Element,0.757556,0.808994,2025.0,0.808994,Goed,2024,0.0,GeenMaatregel,103.551251
1,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.0,Erftoegangsweg,Element,0.757556,0.808994,2025.0,0.791394,Voldoende,2025,1331.2,ElementenPlaatselijkeHerstraten,101.298451
2,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.0,Erftoegangsweg,Element,0.757556,0.808994,2025.0,0.853016,Goed,2026,0.0,GeenMaatregel,109.186063
3,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.0,Erftoegangsweg,Element,0.757556,0.808994,2025.0,0.835416,Goed,2027,0.0,GeenMaatregel,106.933263
4,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.0,Erftoegangsweg,Element,0.757556,0.808994,2025.0,0.817816,Goed,2028,0.0,GeenMaatregel,104.680463
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21795,BB78CA6B-B987-4BC7-A1CF-1D8ABD79EC05,162.0,Erftoegangsweg,Element,0.882653,0.882653,2029.0,0.691326,Voldoende,2039,0.0,GeenMaatregel,111.994884
21796,BB78CA6B-B987-4BC7-A1CF-1D8ABD79EC05,162.0,Erftoegangsweg,Element,0.882653,0.882653,2029.0,0.673726,Voldoende,2040,0.0,GeenMaatregel,109.143684
21797,BB78CA6B-B987-4BC7-A1CF-1D8ABD79EC05,162.0,Erftoegangsweg,Element,0.882653,0.882653,2029.0,0.656126,Voldoende,2041,0.0,GeenMaatregel,106.292484
21798,BB78CA6B-B987-4BC7-A1CF-1D8ABD79EC05,162.0,Erftoegangsweg,Element,0.882653,0.882653,2029.0,0.638526,Voldoende,2042,0.0,GeenMaatregel,103.441284
21799,BB78CA6B-B987-4BC7-A1CF-1D8ABD79EC05,162.0,Erftoegangsweg,Element,0.882653,0.882653,2029.0,0.620926,Voldoende,2043,0.0,GeenMaatregel,100.590084

In [7]:
df_input_holstraat_ERF_ASFALT = df[df.Guid == '9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1']
df_input_holstraat_ERF_ASFALT

,G_staat,G_date,S_index,S_date,WSO_id,V_index,Dofunctie,Verharding,Wegfunctie,Straat,Gemeente,Wegsectie,Guid,Oppervlakt,Prioriteit,DATUM,geometry,functie,verharding
0,0.808994,1950-01-01,0.860432,1950-01-01,0,0.757556,RW,BP,ERF,OUDE HAACHTSESTEENWEG,Machelen,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,9BEE7B45-6FEF-4FCC-B513-2A50D776A3A1,128.195553,1.0,2024-10-06,"POLYGON ((154638.46 176161.767, 154637.994 176...",erf,elementen

In [8]:
df_output_holstraat_ERF_ASFALT = df_output_org[df_output_org.GUID == "FCFB895E-7B02-49C7-855B-DED4F543A8E6"]
df_output_holstraat_ERF_ASFALT[['Kwaliteit', 'Maatregel','verhardingstype', 'Kosten', 'Oppervlakte']]

,Kwaliteit,Maatregel,verhardingstype,Kosten,Oppervlakte
60,0.769092,GeenMaatregel,Element,0.0,74.0
61,0.751492,GeenMaatregel,Element,0.0,74.0
62,0.733892,GeenMaatregel,Element,0.0,74.0
63,0.716292,GeenMaatregel,Element,0.0,74.0
64,0.698692,GeenMaatregel,Element,0.0,74.0
65,0.681092,GeenMaatregel,Element,0.0,74.0
66,0.663492,GeenMaatregel,Element,0.0,74.0
67,0.645892,GeenMaatregel,Element,0.0,74.0
68,0.628292,GeenMaatregel,Element,0.0,74.0
69,0.610692,GeenMaatregel,Element,0.0,74.0
70,0.593092,GeenMaatregel,Element,0.0,74.0
71,0.575492,GeenMaatregel,Element,0.0,74.0
72,0.557892,GeenMaatregel,Element,0.0,74.0
73,0.540292,GeenMaatregel,Element,0.0,74.0
74,0.522692,GeenMaatregel,Element,0.0,74.0
75,0.505092,GeenMaatregel,Element,0.0,74.0
76,0.487492,ElementenVolledigHerstraten,Element,10360.0,74.0
77,0.663346,GeenMaatregel,Element,0.0,74.0
78,0.645746,GeenMaatregel,Element,0.0,74.0
79,0.628146,GeenMaatregel,Element,0.0,74.0

In [9]:
data_file_uwe = "../data/output_ocw/df_all_onderhoud_scenario1.parquet"
df_output_uwe = pd.read_parquet(data_file_uwe)

print(df_output_uwe.shape)
df_output_uwe

FileNotFoundError: [Errno 2] No such file or directory: '../data/output_ocw/df_all_onderhoud_scenario1.parquet'

In [ ]:
scenario = 17
subset = df_output_uwe[df_output_uwe["scenario_nm"] == scenario]
df_test = subset.groupby(['jaar', 'maatregel']).agg({
        'cost': 'sum'
    }).reset_index()

df_test

In [ ]:
def classify_road(global_index: float, use_uncertainty_zones: bool = True):
        """Classify road section based on global index with optional uncertainty zones"""
        if use_uncertainty_zones:
            if global_index >= 0.85: return "Zeer goed"
            elif 0.85 > global_index >= 0.75: return "Goed"
            elif 0.75 > global_index >= 0.55: return "Voldoende"
            elif 0.55 > global_index >= 0.45: return "Net voldoende"
            elif 0.45 > global_index >= 0.35: return "Matig"
            elif 0.35 > global_index >= 0.25: return "Onvoldoende"
            else: return "Zeer slecht"
        else:
            if global_index >= 0.80: return (1, "Zeer goed")
            elif 0.80 > global_index >= 0.50: return (2, "Goed")
            elif 0.50 > global_index >= 0.30: return (3, "Voldoende")
            else: return (4, "Onvoldoende")

df_output_uwe['classify'] = df_output_uwe['globaal_index'].apply(lambda x: classify_road(global_index=x, use_uncertainty_zones=True))

df_output_uwe.info()

In [ ]:
scenario = 18
subset = df_output_uwe[df_output_uwe["scenario_nm"] == scenario]


# Aggregate data by year and quality class
quality_by_year = (subset.groupby(['jaar', 'classify'])
                  .size()
                  .unstack()
                  .fillna(0))

quality_by_year

In [ ]:
df_output_uwe.shape

In [ ]:
df_compare = df_output_uwe.groupby(by=['scenario_nm', 'jaar']).agg(
    {'cost': sum}
).unstack().T

In [ ]:
df_output_uwe.groupby(['scenario_nm', 'jaar'])['cost'].sum().unstack('jaar').T

In [ ]:
from importlib.resources import files

In [ ]:
files("ocw_project")